In [1]:
import pickle
import torch

In [68]:
a = pickle.load(open('predictions_test4lr','rb'))
a= (torch.cat(a)>0.05)*1
a = a.numpy()

In [69]:
a = a[:,[idx for idx,i in enumerate(['Achievement', 'Benevolence', 'Benevolence: caring',
       'Benevolence: dependability', 'Conformity', 'Conformity: interpersonal',
       'Conformity: rules', 'Face', 'Hedonism', 'Humility', 'Power',
       'Power: dominance', 'Power: resources', 'Security',
       'Security: personal', 'Security: societal', 'Self-direction',
       'Self-direction: action', 'Self-direction: thought', 'Stimulation',
       'Tradition', 'Universalism', 'Universalism: concern',
       'Universalism: nature', 'Universalism: objectivity',
       'Universalism: tolerance']) if i not in ['Self-direction', 'Power', 'Security', 'Conformity', 'Benevolence',
       'Universalism']]]

In [52]:
[i for idx,i in enumerate(['Achievement', 'Benevolence', 'Benevolence: caring',
       'Benevolence: dependability', 'Conformity', 'Conformity: interpersonal',
       'Conformity: rules', 'Face', 'Hedonism', 'Humility', 'Power',
       'Power: dominance', 'Power: resources', 'Security',
       'Security: personal', 'Security: societal', 'Self-direction',
       'Self-direction: action', 'Self-direction: thought', 'Stimulation',
       'Tradition', 'Universalism', 'Universalism: concern',
       'Universalism: nature', 'Universalism: objectivity',
       'Universalism: tolerance']) if i not in ['Self-direction', 'Power', 'Security', 'Conformity', 'Benevolence',
       'Universalism']]

['Achievement',
 'Benevolence: caring',
 'Benevolence: dependability',
 'Conformity: interpersonal',
 'Conformity: rules',
 'Face',
 'Hedonism',
 'Humility',
 'Power: dominance',
 'Power: resources',
 'Security: personal',
 'Security: societal',
 'Self-direction: action',
 'Self-direction: thought',
 'Stimulation',
 'Tradition',
 'Universalism: concern',
 'Universalism: nature',
 'Universalism: objectivity',
 'Universalism: tolerance']

In [70]:
a

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [71]:
import pandas as pd
df = pd.read_csv('data/labels-validation.tsv',delimiter='\t')
df2 = pd.read_csv('data/arguments-test.tsv',delimiter='\t')

In [72]:
df2

Argument ID                                         Conclusion  \
0         A26004                   We should end affirmative action   
1         A26010                   We should end affirmative action   
2         A26016                          We should ban naturopathy   
3         A26024                 We should prohibit women in combat   
4         A26026                          We should ban naturopathy   
...          ...                                                ...   
1571      E07272             We should end mass migration together.   
1572      E07273             We should end mass migration together.   
1573      E07275  We should consider Russian interests in the EU...   
1574      E07280  We should adopt an extension of the applicatio...   
1575      E08023               We should abolish covid digital pass   

           Stance                                            Premise  
0         against   affirmative action helps with employment equity.  
1     in favor of  affirmative action can be considered discrimin...  
2     in favor of  naturopathy is very dangerous for the most vul...  
3     in favor of  women shouldn't be in combat because they aren...  
4     in favor of  once eradicated illnesses are returning due to...  
...           ...                                                ...  
1571  in favor of  Mass migration is a phenomenon that causes dam...  
1572  in favor of  Mass migration hurts the migrants themselves i...  
1573  in favor of  It is neither in the interests of the EU nor R...  
1574  in favor of  Foreign Policy at the EU level should be based...  
1575      against  You owe the fact that you can drink your coffe...  

[1576 rows x 4 columns]

In [73]:
a

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [77]:
df.columns

Index(['Argument ID', 'Self-direction: thought', 'Self-direction: action',
       'Stimulation', 'Hedonism', 'Achievement', 'Power: dominance',
       'Power: resources', 'Face', 'Security: personal', 'Security: societal',
       'Tradition', 'Conformity: rules', 'Conformity: interpersonal',
       'Humility', 'Benevolence: caring', 'Benevolence: dependability',
       'Universalism: concern', 'Universalism: nature',
       'Universalism: tolerance', 'Universalism: objectivity'],
      dtype='object')

In [74]:
d= pd.DataFrame(a,columns=df.columns.difference(['Argument ID']))
d['Argument ID'] = df2['Argument ID']
ans =d[df.columns]

In [75]:
ans.to_csv('res_testall.tsv',index=False,sep='\t')

In [12]:
d = pd.read_csv('data/labels-training.tsv',delimiter='\t')

In [15]:
a = d[df.columns.difference(['Argument ID'])].sum()
b=a.sum()/a
c = (b/b.sum()).values

In [16]:
a

Achievement                   1512
Benevolence: caring           1332
Benevolence: dependability     806
Conformity: interpersonal      207
Conformity: rules             1177
Face                           382
Hedonism                       172
Humility                       395
Power: dominance               610
Power: resources               625
Security: personal            2000
Security: societal            1728
Self-direction: action        1395
Self-direction: thought        988
Stimulation                    247
Tradition                      568
Universalism: concern         2081
Universalism: nature           427
Universalism: objectivity     1054
Universalism: tolerance        664
dtype: int64

In [18]:
torch.Tensor(c)

tensor([0.0278, 0.0197, 0.1111, 0.1596, 0.0182, 0.0450, 0.0439, 0.0719, 0.0137,
        0.0159, 0.0483, 0.0233, 0.1326, 0.0695, 0.0206, 0.0341, 0.0132, 0.0643,
        0.0413, 0.0260])

In [29]:
b

Self-direction: thought        18.593117
Self-direction: action         13.168459
Stimulation                    74.372470
Hedonism                      106.802326
Achievement                    12.149471
Power: dominance               30.114754
Power: resources               29.392000
Face                           48.089005
Security: personal              9.185000
Security: societal             10.630787
Tradition                      32.341549
Conformity: rules              15.607477
Conformity: interpersonal      88.743961
Humility                       46.506329
Benevolence: caring            13.791291
Benevolence: dependability     22.791563
Universalism: concern           8.827487
Universalism: nature           43.021077
Universalism: tolerance        27.665663
Universalism: objectivity      17.428843
dtype: float64

In [18]:
import pandas as pd
df = pd.read_csv('data/labels-validation.tsv',delimiter='\t')
# df2 = pd.read_csv('data/arguments-validation.tsv',delimiter='\t')
def extra_labels(df):
    df['Self-direction'] = df[['Self-direction: thought', 'Self-direction: action']].sum(axis=1)
    df['Power'] = df[['Power: dominance','Power: resources']].sum(axis=1)
    df['Security']= df[['Security: personal', 'Security: societal']].sum(axis=1)
    df['Conformity']= df[['Conformity: rules', 'Conformity: interpersonal']].sum(axis=1)
    df['Benevolence']=df[['Benevolence: caring', 'Benevolence: dependability']].sum(axis=1)
    df['Universalism'] =df[['Universalism: concern', 'Universalism: nature','Universalism: tolerance', 'Universalism: objectivity']].sum(axis=1)
    for i in ['Self-direction','Power','Security','Conformity','Benevolence','Universalism']:
        df[i]=(df[i]>0)*1
    # l3 = pd.read_csv('data/labels-level3.tsv',delimiter='\t')
    # l4a = pd.read_csv('data/labels-level4a.tsv',delimiter='\t')
    # l4b = pd.read_csv('data/labels-level4b.tsv',delimiter='\t')
    # print(df['Argument ID'])
    # df = pd.merge(df,l3,on='Argument ID')
    # df = pd.merge(df,l4a,on='Argument ID')
    # df = pd.merge(df,l4b,on='Argument ID')
    return df

df = extra_labels(df)
df[df.columns.difference(['Argument ID'])].columns

Index(['Achievement', 'Benevolence', 'Benevolence: caring',
       'Benevolence: dependability', 'Conformity', 'Conformity: interpersonal',
       'Conformity: rules', 'Face', 'Hedonism', 'Humility', 'Power',
       'Power: dominance', 'Power: resources', 'Security',
       'Security: personal', 'Security: societal', 'Self-direction',
       'Self-direction: action', 'Self-direction: thought', 'Stimulation',
       'Tradition', 'Universalism', 'Universalism: concern',
       'Universalism: nature', 'Universalism: objectivity',
       'Universalism: tolerance'],
      dtype='object')

In [36]:
df = df[df.columns.difference(['Argument ID'])]
# a= df[['Self-direction','Power','Security','Conformity','Benevolence','Universalism']]
# b = df[df.columns.difference(['Self-direction','Power','Security','Conformity','Benevolence','Universalism'])]
b_cols =[i for i in ['Achievement', 'Benevolence', 'Benevolence: caring',
       'Benevolence: dependability', 'Conformity', 'Conformity: interpersonal',
       'Conformity: rules', 'Face', 'Hedonism', 'Humility', 'Power',
       'Power: dominance', 'Power: resources', 'Security',
       'Security: personal', 'Security: societal', 'Self-direction',
       'Self-direction: action', 'Self-direction: thought', 'Stimulation',
       'Tradition', 'Universalism', 'Universalism: concern',
       'Universalism: nature', 'Universalism: objectivity',
       'Universalism: tolerance'] if i not in ['Self-direction', 'Power', 'Security', 'Conformity', 'Benevolence',
       'Universalism']]
a_cols =['Self-direction', 'Power', 'Security', 'Conformity', 'Benevolence',
       'Universalism']
b = df[b_cols]
a = df[a_cols]
# d = df[['Personal focus', 'Social focus']]
# e = df[['Growth, Anxiety-free', 'Self-protection, Anxiety avoidance']]

In [38]:
b.sum()

Achievement                   575
Benevolence: caring           633
Benevolence: dependability    268
Conformity: interpersonal      60
Conformity: rules             455
Face                          130
Hedonism                      103
Humility                      127
Power: dominance              164
Power: resources              132
Security: personal            759
Security: societal            488
Self-direction: action        496
Self-direction: thought       251
Stimulation                   138
Tradition                     172
Universalism: concern         687
Universalism: nature          127
Universalism: objectivity     371
Universalism: tolerance       223
dtype: int64

In [20]:
ans_a = sum(a.sum())/a.sum()
ans_a=ans_a/ans_a.sum()

ans_b = sum(b.sum())/b.sum()
ans_b = ans_b/ans_b.sum()

In [34]:
finn = pd.concat([8*ans_b,2*ans_a]).sort_index()
finn

Achievement                   0.134037
Benevolence                   0.243516
Benevolence: caring           0.121756
Benevolence: dependability    0.287580
Conformity                    0.404186
Conformity: interpersonal     1.284526
Conformity: rules             0.169388
Face                          0.592858
Hedonism                      0.748267
Humility                      0.606862
Power                         0.675966
Power: dominance              0.469948
Power: resources              0.583875
Security                      0.176763
Security: personal            0.101544
Security: societal            0.157933
Self-direction                0.321361
Self-direction: action        0.155386
Self-direction: thought       0.307058
Stimulation                   0.558489
Tradition                     0.448090
Universalism                  0.178209
Universalism: concern         0.112186
Universalism: nature          0.606862
Universalism: objectivity     0.207740
Universalism: tolerance  

In [38]:
ans_=[]
for i,j in zip([b,c],pd.Series([20,4])/3.4):
    x = sum(i.sum())/i.sum()
    x = x/x.sum()
    ans_.append(j*x)
fin_weights = pd.concat(ans_) 

In [40]:
fin_weights.values

array([0.18032029, 0.10405367, 0.29385528, 0.46671133, 0.1027067 ,
       0.41216066, 0.44699113, 0.42886987, 0.06854508, 0.11710838,
       0.29660159, 0.10721747, 0.73805513, 0.36064057, 0.07759504,
       0.19712031, 0.08075412, 0.99176158, 0.22349557, 0.18778917,
       0.38908921, 0.37332653, 0.21069813, 0.20335673])

In [40]:
final = pd.concat([8*ans_b,2*ans_a])

In [41]:
final.values

array([0.30705791, 0.15538616, 0.55848939, 0.74826734, 0.13403745,
       0.46994839, 0.58387527, 0.59285797, 0.10154353, 0.15793347,
       0.44809032, 0.16938799, 1.2845256 , 0.60686249, 0.12175598,
       0.28758036, 0.11218564, 0.60686249, 0.34561227, 0.20773999,
       0.32136078, 0.67596578, 0.17676292, 0.40418573, 0.24351562,
       0.17820916])

In [39]:
from transformers import AutoModel,AutoTokenizer
import pytorch_lightning as pl


from pytorch_lightning import Trainer
from sklearn.metrics import classification_report


import pickle



import torch.optim as optim

model = AutoModel.from_pretrained("microsoft/deberta-base")
tokenizer = AutoTokenizer.from_pretrained("microsoft/deberta-base")

Some weights of the model checkpoint at microsoft/deberta-base were not used when initializing DebertaModel: ['lm_predictions.lm_head.bias', 'lm_predictions.lm_head.dense.bias', 'lm_predictions.lm_head.LayerNorm.weight', 'lm_predictions.lm_head.LayerNorm.bias', 'lm_predictions.lm_head.dense.weight']
- This IS expected if you are initializing DebertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DebertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [45]:
from torch.utils.data import Dataset,DataLoader
import numpy as np
def extra_labels(df):
    df['Self-direction'] = df[['Self-direction: thought', 'Self-direction: action']].sum(axis=1)
    df['Power'] = df[['Power: dominance','Power: resources']].sum(axis=1)
    df['Security']= df[['Security: personal', 'Security: societal']].sum(axis=1)
    df['Conformity']= df[['Conformity: rules', 'Conformity: interpersonal']].sum(axis=1)
    df['Benevolence']=df[['Benevolence: caring', 'Benevolence: dependability']].sum(axis=1)
    df['Universalism'] =df[['Universalism: concern', 'Universalism: nature','Universalism: tolerance', 'Universalism: objectivity']].sum(axis=1)
    for i in ['Self-direction','Power','Security','Conformity','Benevolence','Universalism']:
        df[i]=(df[i]>0)*1


    return df

class Data(Dataset):
    def __init__(self,tokenizer,split="training") -> None:
        super().__init__()
        df = pd.read_csv('data/arguments-training.tsv',delimiter='\t')
        df2 = pd.read_csv('data/arguments-validation.tsv',delimiter='\t')
        df3 = pd.read_csv('data/arguments-validation-zhihu.tsv',delimiter='\t')
        df = pd.concat([df,df2,df3])
        if split!='test':
            ldf = pd.read_csv('data/labels-training.tsv',delimiter='\t')
            ldf2 = pd.read_csv('data/labels-validation.tsv',delimiter='\t')
            ldf3 = pd.read_csv('data/labels-validation-zhihu.tsv',delimiter='\t')
            df = df.merge(ldf,on=["Argument ID"])
            df = extra_labels(df)
            self.labels = df[df.columns.difference(['Argument ID','Conclusion','Stance','Premise'])].values
        
        self.argument_ids  = df['Argument ID'].values
        self.conclusion =df['Conclusion'].values
        self.stance  = df['Stance'].values
        self.premise = df['Premise'].values
        self.tokenizer =tokenizer
        self.split=split

    def __len__(self):
        return len(self.argument_ids)
    
    def __getitem__(self,idx):
        return_dict =  {"premise":self.tokenizer(self.premise[idx],add_special_tokens=False)['input_ids'],
                "stance":self.tokenizer(self.stance[idx],add_special_tokens=False)['input_ids'],
                "conclusion":self.tokenizer(self.conclusion[idx],add_special_tokens=False)['input_ids'],
                }
        if self.split!='test':
            return_dict["labels"]=self.labels[idx]
        return return_dict


def collate_fn(batch):
    unpadded_batch=[]
    for row in batch:
        i,j,k = row['premise'],row['stance'],row['conclusion']
        unpadded_batch.append([1]+i+[2]+j+[2]+k+[2])
    max_len = max([len(i) for i in unpadded_batch])
    x = np.array([i+[0]*(max_len-len(i)) for i in unpadded_batch])
    
    return torch.LongTensor(x),(torch.Tensor(np.array([row['labels'] for row in batch])) if 'labels' in batch[0] else None)


    


In [46]:

train_loader = DataLoader(Data(tokenizer,"training"),batch_size=16,collate_fn=collate_fn,shuffle=True)


In [48]:
for i in train_loader:
    print(i[0].shape,i[1].shape)
    break

torch.Size([16, 82]) torch.Size([16, 26])


In [49]:
len(train_loader)

338